# Generated by Django 2.2.4 on 2019-10-07 18:39

from django.db import migrations, models
import three_server.base.model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=24, verbose_name='键')),
                ('value', models.CharField(max_length=200, verbose_name='值')),
                ('type', models.CharField(max_length=200, verbose_name='类型')),
            ],
            options={
                'default_permissions': (),
                'abstract': False,
            },
            bases=(models.Model, three_server.base.model.DictMixin),
        ),
    ]
