# Generated by Django 2.2.4 on 2019-10-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyvalue',
            name='key',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='键'),
        ),
        migrations.AlterField(
            model_name='keyvalue',
            name='value',
            field=models.TextField(verbose_name='值'),
        ),
    ]
