# Generated by Django 2.2.4 on 2019-10-07 18:39

from django.db import migrations, models
import three_server.base.model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=36, verbose_name='银行名称')),
                ('number', models.TextField(default='', unique=True, verbose_name='账户号码')),
                ('user_name', models.CharField(default='', max_length=24, verbose_name='名称')),
                ('amount_max', models.IntegerField(default=0, verbose_name='最大金额')),
                ('amount_min', models.IntegerField(default=0, verbose_name='最小金额')),
                ('active', models.BooleanField(default=False, verbose_name='激活')),
            ],
            options={
                'db_table': 'finance_bank_account',
            },
            bases=(models.Model, three_server.base.model.DictMixin),
        ),
        migrations.CreateModel(
            name='BankOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=24, unique=True, verbose_name='银行名称')),
                ('active', models.BooleanField(default=True, verbose_name='是否激活')),
            ],
            options={
                'db_table': 'finance_bank_option',
            },
            bases=(models.Model, three_server.base.model.DictMixin),
        ),
        migrations.CreateModel(
            name='FastAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('account_name', models.CharField(max_length=24, verbose_name='账户名称')),
                ('account_number', models.CharField(default='', max_length=24, verbose_name='账户账号')),
                ('qr_code', models.TextField(default='', verbose_name='二维码')),
                ('active', models.BooleanField(default=False, verbose_name='激活')),
            ],
            options={
                'db_table': 'finance_fast_account',
            },
            bases=(models.Model, three_server.base.model.DictMixin),
        ),
        migrations.CreateModel(
            name='RechargeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('depositor', models.CharField(max_length=24, verbose_name='存款人')),
                ('pay_money', models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='充值金额')),
                ('type', models.CharField(max_length=24, verbose_name='类型')),
                ('payee', models.CharField(max_length=24, verbose_name='收款人')),
                ('account_id', models.CharField(max_length=124, verbose_name='收款账户')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('remark', models.CharField(default='', max_length=128, verbose_name='备注')),
            ],
            options={
                'db_table': 'finance_recharge_record',
            },
            bases=(models.Model, three_server.base.model.DictMixin),
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='金币')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('remark', models.CharField(default='', max_length=128, verbose_name='备注')),
            ],
            options={
                'default_permissions': (),
                'abstract': False,
            },
            bases=(models.Model, three_server.base.model.DictMixin),
        ),
    ]
