# Generated by Django 2.2.4 on 2019-10-07 18:39

from django.db import migrations, models
import three_server.base.model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='', max_length=6, verbose_name='标题')),
                ('icon', models.CharField(default='', max_length=6, verbose_name='图标')),
                ('content_type', models.CharField(default='TEXT', max_length=12, verbose_name='内容类型')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('drive_type', models.CharField(default='NORMAL', max_length=12, verbose_name='活动类型')),
            ],
            options={
                'default_permissions': (),
                'abstract': False,
            },
            bases=(models.Model, three_server.base.model.DictMixin),
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(default='', verbose_name='内容')),
            ],
            options={
                'default_permissions': (),
                'abstract': False,
            },
            bases=(models.Model, three_server.base.model.DictMixin),
        ),
    ]
