# Generated by Django 2.2.4 on 2019-10-07 18:39

from django.db import migrations, models
import django.db.models.deletion
import three_server.base.model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('hall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'default_permissions': (),
                'abstract': False,
            },
            bases=(models.Model, three_server.base.model.DictMixin),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=24, verbose_name='玩家名称')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('serial', models.CharField(max_length=200, verbose_name='玩家序列号')),
                ('token', models.CharField(default='', max_length=200, verbose_name='密钥')),
                ('phone', models.CharField(max_length=100, verbose_name='手机号')),
                ('avatar', models.CharField(default='', max_length=200, verbose_name='头像')),
                ('gold', models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='金币')),
                ('integral', models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='积分')),
                ('status', models.CharField(default='', max_length=200, verbose_name='状态')),
                ('own_invite_code', models.CharField(default='', max_length=50, verbose_name='邀请码')),
                ('invite_code', models.CharField(default='', max_length=50, verbose_name='注册邀请码')),
            ],
            options={
                'default_permissions': (),
                'abstract': False,
            },
            bases=(models.Model, three_server.base.model.DictMixin),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=24, verbose_name='姓名')),
                ('number', models.CharField(max_length=32, verbose_name='号码')),
                ('bank_branch', models.CharField(default='', max_length=128, verbose_name='开户行支行')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.BankOption', verbose_name='银行')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player', verbose_name='玩家')),
            ],
            options={
                'default_permissions': (),
                'abstract': False,
            },
            bases=(models.Model, three_server.base.model.DictMixin),
        ),
        migrations.CreateModel(
            name='BetRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('bet_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='下注金额')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='中奖金额')),
                ('bet_type', models.CharField(default='', max_length=16, verbose_name='投注类型')),
                ('state', models.IntegerField(default=0, verbose_name='状态')),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='player.Player', verbose_name='玩家')),
                ('sequence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hall.Result', to_field='sequence', verbose_name='大厅期号')),
            ],
            options={
                'default_permissions': (),
                'abstract': False,
            },
            bases=(models.Model, three_server.base.model.DictMixin),
        ),
    ]
