# Generated by Django 2.2.4 on 2019-10-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='lock_gold',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='锁定资金'),
        ),
    ]
