# Generated by Django 2.2.4 on 2019-10-07 18:39

from django.db import migrations, models
import django.db.models.deletion
import three_server.base.model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignReward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('sign_day', models.IntegerField(default=0, unique=True, verbose_name='签到天数')),
                ('reward_type', models.CharField(default=0, max_length=12, verbose_name='奖励类型')),
                ('reward_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='奖励值')),
            ],
            options={
                'default_permissions': (),
                'abstract': False,
            },
            bases=(models.Model, three_server.base.model.DictMixin),
        ),
        migrations.CreateModel(
            name='SignRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.IntegerField(default=0, verbose_name='开始签到时间')),
                ('end_time', models.IntegerField(default=0, verbose_name='结束签到时间')),
                ('total', models.IntegerField(default=0, verbose_name='总计天数')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='player.Player', verbose_name='玩家')),
            ],
            options={
                'default_permissions': (),
                'abstract': False,
            },
            bases=(models.Model, three_server.base.model.DictMixin),
        ),
    ]
