# Generated by Django 2.2.4 on 2019-10-07 18:39

from django.db import migrations, models
import django.db.models.deletion
import three_server.base.model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('mail_type', models.CharField(max_length=24, verbose_name='邮件类型')),
                ('tag', models.CharField(default='', max_length=12, verbose_name='标签')),
                ('title', models.CharField(default='', max_length=24, verbose_name='标题')),
                ('content_type', models.TextField(default='', verbose_name='内容类型')),
                ('content', models.CharField(default='', max_length=124, verbose_name='内容')),
                ('exist_annex', models.BooleanField(default=False, verbose_name='存在附件')),
                ('annex', models.CharField(default='', max_length=1024, verbose_name='附件')),
            ],
            options={
                'default_permissions': (),
                'abstract': False,
            },
            bases=(models.Model, three_server.base.model.DictMixin),
        ),
        migrations.CreateModel(
            name='MailPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='是否读取')),
                ('is_receive', models.BooleanField(default=False, verbose_name='是否领取')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mail.Mail', verbose_name='邮件')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player', verbose_name='玩家')),
            ],
            options={
                'default_permissions': (),
                'abstract': False,
            },
            bases=(models.Model, three_server.base.model.DictMixin),
        ),
    ]
