# Generated by Django 2.2.4 on 2019-10-07 18:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import three_server.base.model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=24, verbose_name='大厅名称')),
                ('tag', models.CharField(default='', max_length=24, unique=True, verbose_name='大厅标签')),
                ('bet_type', models.IntegerField(default=0, verbose_name='下注类型')),
                ('lottery_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开奖时间')),
                ('lottery_type', models.CharField(default='Self', max_length=24, verbose_name='开奖类型')),
                ('game_date', models.IntegerField(default=0, verbose_name='每局时间')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('active', models.BooleanField(default=False, verbose_name='激活')),
                ('stage', models.CharField(default='StartStage', max_length=24, verbose_name='大厅阶段')),
                ('total', models.IntegerField(default=0, verbose_name='总局数')),
            ],
            options={
                'default_permissions': (),
                'abstract': False,
            },
            bases=(models.Model, three_server.base.model.DictMixin),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.CharField(max_length=24, unique=True, verbose_name='期号')),
                ('bet_count', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='下注统计')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='开奖金额')),
                ('result', models.CharField(default='', max_length=24, verbose_name='开奖结果')),
                ('big', models.BooleanField(default=False, verbose_name='大')),
                ('even', models.BooleanField(default=False, verbose_name='双')),
                ('sum', models.IntegerField(default=0, verbose_name='值')),
                ('hall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hall.Hall', verbose_name='大厅')),
            ],
            options={
                'default_permissions': (),
                'abstract': False,
            },
            bases=(models.Model, three_server.base.model.DictMixin),
        ),
        migrations.CreateModel(
            name='HallChipOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('position', models.IntegerField(default=0, verbose_name='位置')),
                ('active', models.BooleanField(default=False, verbose_name='显示')),
                ('value', models.IntegerField(default=0, verbose_name='面值')),
                ('hall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hall.Hall', verbose_name='大厅')),
            ],
            options={
                'default_permissions': (),
                'abstract': False,
            },
            bases=(models.Model, three_server.base.model.DictMixin),
        ),
        migrations.CreateModel(
            name='HallBetOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('position', models.IntegerField(default=0, verbose_name='位置')),
                ('dice_type', models.CharField(default='', max_length=24, verbose_name='骰型')),
                ('active', models.BooleanField(default=False, verbose_name='显示')),
                ('odds', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='赔率')),
                ('hall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hall.Hall', verbose_name='大厅')),
            ],
            options={
                'default_permissions': (),
                'abstract': False,
            },
            bases=(models.Model, three_server.base.model.DictMixin),
        ),
    ]
