# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='chat.proto',
  package='com.im.common.packets',
  syntax='proto3',
  serialized_options=_b('\n\025com.im.common.packetsP\001'),
  serialized_pb=_b('\n\nchat.proto\x12\x15\x63om.im.common.packets\"\x85\x01\n\x0b\x43hatReqBody\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12-\n\x04type\x18\x02 \x01(\x0e\x32\x1f.com.im.common.packets.ChatType\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\r\n\x05group\x18\x04 \x01(\t\x12\x0c\n\x04toId\x18\x05 \x01(\x05\x12\x0e\n\x06toNick\x18\x06 \x01(\t\"\xa8\x01\n\x0c\x43hatRespBody\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12-\n\x04type\x18\x02 \x01(\x0e\x32\x1f.com.im.common.packets.ChatType\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\x0e\n\x06\x66romId\x18\x04 \x01(\x05\x12\x10\n\x08\x66romNick\x18\x05 \x01(\t\x12\x0c\n\x04toId\x18\x06 \x01(\x05\x12\x0e\n\x06toNick\x18\x07 \x01(\t\x12\r\n\x05group\x18\x08 \x01(\t*M\n\x08\x43hatType\x12\x14\n\x10\x43HAT_TYPE_UNKNOW\x10\x00\x12\x14\n\x10\x43HAT_TYPE_PUBLIC\x10\x01\x12\x15\n\x11\x43HAT_TYPE_PRIVATE\x10\x02\x42\x19\n\x15\x63om.im.common.packetsP\x01\x62\x06proto3')
)

_CHATTYPE = _descriptor.EnumDescriptor(
  name='ChatType',
  full_name='com.im.common.packets.ChatType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CHAT_TYPE_UNKNOW', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHAT_TYPE_PUBLIC', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHAT_TYPE_PRIVATE', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=344,
  serialized_end=421,
)
_sym_db.RegisterEnumDescriptor(_CHATTYPE)

ChatType = enum_type_wrapper.EnumTypeWrapper(_CHATTYPE)
CHAT_TYPE_UNKNOW = 0
CHAT_TYPE_PUBLIC = 1
CHAT_TYPE_PRIVATE = 2



_CHATREQBODY = _descriptor.Descriptor(
  name='ChatReqBody',
  full_name='com.im.common.packets.ChatReqBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='com.im.common.packets.ChatReqBody.time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='com.im.common.packets.ChatReqBody.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='com.im.common.packets.ChatReqBody.text', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='group', full_name='com.im.common.packets.ChatReqBody.group', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='toId', full_name='com.im.common.packets.ChatReqBody.toId', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='toNick', full_name='com.im.common.packets.ChatReqBody.toNick', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=171,
)


_CHATRESPBODY = _descriptor.Descriptor(
  name='ChatRespBody',
  full_name='com.im.common.packets.ChatRespBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='com.im.common.packets.ChatRespBody.time', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='com.im.common.packets.ChatRespBody.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='com.im.common.packets.ChatRespBody.text', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fromId', full_name='com.im.common.packets.ChatRespBody.fromId', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fromNick', full_name='com.im.common.packets.ChatRespBody.fromNick', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='toId', full_name='com.im.common.packets.ChatRespBody.toId', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='toNick', full_name='com.im.common.packets.ChatRespBody.toNick', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='group', full_name='com.im.common.packets.ChatRespBody.group', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=342,
)

_CHATREQBODY.fields_by_name['type'].enum_type = _CHATTYPE
_CHATRESPBODY.fields_by_name['type'].enum_type = _CHATTYPE
DESCRIPTOR.message_types_by_name['ChatReqBody'] = _CHATREQBODY
DESCRIPTOR.message_types_by_name['ChatRespBody'] = _CHATRESPBODY
DESCRIPTOR.enum_types_by_name['ChatType'] = _CHATTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChatReqBody = _reflection.GeneratedProtocolMessageType('ChatReqBody', (_message.Message,), {
  'DESCRIPTOR' : _CHATREQBODY,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:com.im.common.packets.ChatReqBody)
  })
_sym_db.RegisterMessage(ChatReqBody)

ChatRespBody = _reflection.GeneratedProtocolMessageType('ChatRespBody', (_message.Message,), {
  'DESCRIPTOR' : _CHATRESPBODY,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:com.im.common.packets.ChatRespBody)
  })
_sym_db.RegisterMessage(ChatRespBody)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
