# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OTIpcDef.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='OTIpcDef.proto',
  package='com.data.upload.proto',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0eOTIpcDef.proto\x12\x15\x63om.data.upload.proto\"\xc6\x02\n\x0f\x42\x61seInfoCompany\x12\x11\n\tCompanyId\x18\x01 \x02(\t\x12\x13\n\x0b\x43ompanyName\x18\x02 \x02(\t\x12\x12\n\nIdentifier\x18\x03 \x02(\t\x12\x0f\n\x07\x41\x64\x64ress\x18\x04 \x02(\r\x12\x15\n\rBusinessScope\x18\x05 \x02(\t\x12\x16\n\x0e\x43ontactAddress\x18\x06 \x02(\t\x12\x14\n\x0c\x45\x63onomicType\x18\x07 \x02(\t\x12\x12\n\nRegCapital\x18\x08 \x02(\t\x12\x11\n\tLegalName\x18\t \x02(\t\x12\x0f\n\x07LegalID\x18\n \x02(\t\x12\x12\n\nLegalPhone\x18\x0b \x02(\t\x12\x12\n\nLegalPhoto\x18\x0c \x01(\t\x12\r\n\x05State\x18\r \x02(\r\x12\x0c\n\x04\x46lag\x18\x0e \x02(\r\x12\x12\n\nUpdateTime\x18\x0f \x02(\x04\x12\x10\n\x08Reserved\x18\x10 \x01(\t\"\x83\x01\n\x13\x42\x61seInfoCompanyStat\x12\x11\n\tCompanyId\x18\x01 \x02(\t\x12\x12\n\nVehicleNum\x18\x02 \x02(\r\x12\x11\n\tDriverNum\x18\x03 \x02(\r\x12\x0c\n\x04\x46lag\x18\x04 \x02(\r\x12\x12\n\nUpdateTime\x18\x05 \x02(\x04\x12\x10\n\x08Reserved\x18\x06 \x01(\t\"\xe7\x01\n\x05OTIpc\x12\x11\n\tCompanyId\x18\x01 \x02(\t\x12\x0e\n\x06Source\x18\x02 \x02(\t\x12/\n\x07IPCType\x18\x03 \x02(\x0e\x32\x1e.com.data.upload.proto.IpcType\x12@\n\x0f\x62\x61seInfoCompany\x18\x81  \x03(\x0b\x32&.com.data.upload.proto.BaseInfoCompany\x12H\n\x13\x62\x61seInfoCompanyStat\x18\x82  \x03(\x0b\x32*.com.data.upload.proto.BaseInfoCompanyStat\"8\n\tOTIpcList\x12+\n\x05otpic\x18\x01 \x03(\x0b\x32\x1c.com.data.upload.proto.OTIpc*9\n\x07IpcType\x12\x14\n\x0f\x62\x61seInfoCompany\x10\x81 \x12\x18\n\x13\x62\x61seInfoCompanyStat\x10\x82 ')
)

_IPCTYPE = _descriptor.EnumDescriptor(
  name='IpcType',
  full_name='com.data.upload.proto.IpcType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='baseInfoCompany', index=0, number=4097,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='baseInfoCompanyStat', index=1, number=4098,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=796,
  serialized_end=853,
)
_sym_db.RegisterEnumDescriptor(_IPCTYPE)

IpcType = enum_type_wrapper.EnumTypeWrapper(_IPCTYPE)
baseInfoCompany = 4097
baseInfoCompanyStat = 4098



_BASEINFOCOMPANY = _descriptor.Descriptor(
  name='BaseInfoCompany',
  full_name='com.data.upload.proto.BaseInfoCompany',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='CompanyId', full_name='com.data.upload.proto.BaseInfoCompany.CompanyId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CompanyName', full_name='com.data.upload.proto.BaseInfoCompany.CompanyName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Identifier', full_name='com.data.upload.proto.BaseInfoCompany.Identifier', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Address', full_name='com.data.upload.proto.BaseInfoCompany.Address', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='BusinessScope', full_name='com.data.upload.proto.BaseInfoCompany.BusinessScope', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ContactAddress', full_name='com.data.upload.proto.BaseInfoCompany.ContactAddress', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='EconomicType', full_name='com.data.upload.proto.BaseInfoCompany.EconomicType', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='RegCapital', full_name='com.data.upload.proto.BaseInfoCompany.RegCapital', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='LegalName', full_name='com.data.upload.proto.BaseInfoCompany.LegalName', index=8,
      number=9, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='LegalID', full_name='com.data.upload.proto.BaseInfoCompany.LegalID', index=9,
      number=10, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='LegalPhone', full_name='com.data.upload.proto.BaseInfoCompany.LegalPhone', index=10,
      number=11, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='LegalPhoto', full_name='com.data.upload.proto.BaseInfoCompany.LegalPhoto', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='State', full_name='com.data.upload.proto.BaseInfoCompany.State', index=12,
      number=13, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Flag', full_name='com.data.upload.proto.BaseInfoCompany.Flag', index=13,
      number=14, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='UpdateTime', full_name='com.data.upload.proto.BaseInfoCompany.UpdateTime', index=14,
      number=15, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Reserved', full_name='com.data.upload.proto.BaseInfoCompany.Reserved', index=15,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=368,
)


_BASEINFOCOMPANYSTAT = _descriptor.Descriptor(
  name='BaseInfoCompanyStat',
  full_name='com.data.upload.proto.BaseInfoCompanyStat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='CompanyId', full_name='com.data.upload.proto.BaseInfoCompanyStat.CompanyId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='VehicleNum', full_name='com.data.upload.proto.BaseInfoCompanyStat.VehicleNum', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='DriverNum', full_name='com.data.upload.proto.BaseInfoCompanyStat.DriverNum', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Flag', full_name='com.data.upload.proto.BaseInfoCompanyStat.Flag', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='UpdateTime', full_name='com.data.upload.proto.BaseInfoCompanyStat.UpdateTime', index=4,
      number=5, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Reserved', full_name='com.data.upload.proto.BaseInfoCompanyStat.Reserved', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=371,
  serialized_end=502,
)


_OTIPC = _descriptor.Descriptor(
  name='OTIpc',
  full_name='com.data.upload.proto.OTIpc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='CompanyId', full_name='com.data.upload.proto.OTIpc.CompanyId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Source', full_name='com.data.upload.proto.OTIpc.Source', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IPCType', full_name='com.data.upload.proto.OTIpc.IPCType', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=4097,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='baseInfoCompany', full_name='com.data.upload.proto.OTIpc.baseInfoCompany', index=3,
      number=4097, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='baseInfoCompanyStat', full_name='com.data.upload.proto.OTIpc.baseInfoCompanyStat', index=4,
      number=4098, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=505,
  serialized_end=736,
)


_OTIPCLIST = _descriptor.Descriptor(
  name='OTIpcList',
  full_name='com.data.upload.proto.OTIpcList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='otpic', full_name='com.data.upload.proto.OTIpcList.otpic', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=738,
  serialized_end=794,
)

_OTIPC.fields_by_name['IPCType'].enum_type = _IPCTYPE
_OTIPC.fields_by_name['baseInfoCompany'].message_type = _BASEINFOCOMPANY
_OTIPC.fields_by_name['baseInfoCompanyStat'].message_type = _BASEINFOCOMPANYSTAT
_OTIPCLIST.fields_by_name['otpic'].message_type = _OTIPC
DESCRIPTOR.message_types_by_name['BaseInfoCompany'] = _BASEINFOCOMPANY
DESCRIPTOR.message_types_by_name['BaseInfoCompanyStat'] = _BASEINFOCOMPANYSTAT
DESCRIPTOR.message_types_by_name['OTIpc'] = _OTIPC
DESCRIPTOR.message_types_by_name['OTIpcList'] = _OTIPCLIST
DESCRIPTOR.enum_types_by_name['IpcType'] = _IPCTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BaseInfoCompany = _reflection.GeneratedProtocolMessageType('BaseInfoCompany', (_message.Message,), {
  'DESCRIPTOR' : _BASEINFOCOMPANY,
  '__module__' : 'OTIpcDef_pb2'
  # @@protoc_insertion_point(class_scope:com.data.upload.proto.BaseInfoCompany)
  })
_sym_db.RegisterMessage(BaseInfoCompany)

BaseInfoCompanyStat = _reflection.GeneratedProtocolMessageType('BaseInfoCompanyStat', (_message.Message,), {
  'DESCRIPTOR' : _BASEINFOCOMPANYSTAT,
  '__module__' : 'OTIpcDef_pb2'
  # @@protoc_insertion_point(class_scope:com.data.upload.proto.BaseInfoCompanyStat)
  })
_sym_db.RegisterMessage(BaseInfoCompanyStat)

OTIpc = _reflection.GeneratedProtocolMessageType('OTIpc', (_message.Message,), {
  'DESCRIPTOR' : _OTIPC,
  '__module__' : 'OTIpcDef_pb2'
  # @@protoc_insertion_point(class_scope:com.data.upload.proto.OTIpc)
  })
_sym_db.RegisterMessage(OTIpc)

OTIpcList = _reflection.GeneratedProtocolMessageType('OTIpcList', (_message.Message,), {
  'DESCRIPTOR' : _OTIPCLIST,
  '__module__' : 'OTIpcDef_pb2'
  # @@protoc_insertion_point(class_scope:com.data.upload.proto.OTIpcList)
  })
_sym_db.RegisterMessage(OTIpcList)


# @@protoc_insertion_point(module_scope)
